set fish_color_autosuggestion       8e908c
set fish_color_command              8959a8
set fish_color_comment              eab700
set fish_color_cwd                  blue
set fish_color_cwd_root             red
set fish_color_end                  8959a8
set fish_color_error                c82829
set fish_color_escape               bryellow\x1e\x2d\x2dbold
set fish_color_history_current      \x2d\x2dbold
set fish_color_host                 normal
set fish_color_match                \x2d\x2dbackground\x3dbrblue
set fish_color_normal               normal
set fish_color_operator             green
set fish_color_param                4271ae
set fish_color_quote                718c00
set fish_color_redirection          3e999f
set fish_color_search_match         bryellow\x1e\x2d\x2dbackground\x3dbrblack
set fish_color_selection            white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set fish_color_status               red
set fish_color_user                 brgreen
set fish_color_valid_path           \x2d\x2dunderline
set fish_pager_color_completion     \x1d
set fish_pager_color_description    B3A06D\x1eyellow
set fish_pager_color_prefix         white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set fish_pager_color_progress       brwhite\x1e\x2d\x2dbackground\x3dcyan
